#application: money-transfer-prototype
#version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: html/css
  
- url: /img
  static_dir: html/img

# default entry  
- url: /
  static_files: html/index.html
  upload: html/index.html

# static website, no python modules are used yet  
- url: /(.*)
  static_files: html/\1
  upload: html/(.*)

  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
